title: <a href="https://quantcert.github.io" style="text-decorations:none; color:inherit;">QuantCert</a>
description: QuantCert is a project aroud quantum computing certification

markdown: kramdown
theme: jekyll-theme-slate

show_downloads: true
