title: QuantCert
description: QuantCert is a project aroud quantum computing certification

markdown: kramdown
theme: jekyll-theme-slate

show_downloads: true

plugins:
  - jekyll-maps
  
maps:
  google:
    api_key: AIzaSyAeRfw7BxDPwcPGeKJSoSv1zN7ScMFjL5E
