title: QuantCert
description: QuantCert is a project aroud quantum computing certification

markdown: kramdown
theme: jekyll-theme-slate

show_downloads: true
include: ["_static", "_sources", "_modules"]
